language: python
cache: pip
dist: bionic

python:
- 3.6
- 3.7
- 3.8

addons:
  postgresql: '10'

env:
  global:
  - SECRET_KEY=thisisnotaverysecretkey
  - DATABASE=postgresql://@/isimip_data
  - DATABASE_METADATA=postgresql://@/isimip_metadata
  - FILES_BASE_URL=http://isimip/
  - PROTOCOL_LOCATION=testing/protocol

before_install:
- sudo apt-get -qq update

install:
- pip install --upgrade pip setuptools wheel
- pip install -r requirements/dev.txt
- pip install coveralls

before_script:
- createdb test_isimip_data
- createdb test_isimip_metadata
- psql test_isimip_metadata -U postgres -f testing/sql/test_isimip_metadata.sql

script:
- pytest --reuse-db --cov=isimip_data

after_success:
- coveralls
