# Generated by Django 3.2.5 on 2021-10-18 10:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annotations', '0007_alter_annotation_specifiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('downloads', models.ManyToManyField(related_name='indicators', to='annotations.Download')),
                ('figures', models.ManyToManyField(related_name='indicators', to='annotations.Figure')),
                ('references', models.ManyToManyField(related_name='indicators', to='annotations.Reference')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('specifiers', models.JSONField(default=dict)),
                ('version_after', models.CharField(blank=True, max_length=8)),
                ('version_before', models.CharField(blank=True, max_length=8)),
                ('datasets', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='indicators.indicator')),
            ],
        ),
    ]
