# Generated by Django 3.2.7 on 2021-10-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicatorvalue',
            options={'ordering': ('indicator',)},
        ),
        migrations.AddField(
            model_name='indicator',
            name='maximum',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='indicator',
            name='minimum',
            field=models.FloatField(default=0),
        ),
    ]
