# Generated by Django 3.2.5 on 2021-11-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0002_add_minimum_maximum'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='reverse',
            field=models.BooleanField(default=False),
        ),
    ]
