# Generated by Django 3.2.5 on 2021-11-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_indicator_reverse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='maximum',
            field=models.FloatField(default=1, help_text='The maximum value for the scale visualization of this indicator.'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='minimum',
            field=models.FloatField(default=0, help_text='The minimum value for the scale visualization of this indicator.'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='reverse',
            field=models.BooleanField(default=False, help_text='Designates whether the values of this indicator should be ordered from small to large.'),
        ),
    ]
