# Generated by Django 3.0.6 on 2021-02-15 11:18

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caveat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('severity', models.TextField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical')])),
                ('status', models.TextField(choices=[('new', 'new'), ('on_hold', 'on hold'), ('resolved', 'resolved'), ('wont_fix', "won't fix")])),
                ('specifiers', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('datasets', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('version_after', models.CharField(blank=True, max_length=8)),
                ('version_before', models.CharField(blank=True, max_length=8)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('updated',),
            },
        ),
    ]
