# Generated by Django 3.0.6 on 2021-02-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caveats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caveat',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caveat',
            name='version_after',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='caveat',
            name='version_before',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
