# Generated by Django 3.0.6 on 2021-02-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
        ('caveats', '0004_add_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='caveat',
            name='figures',
            field=models.ManyToManyField(related_name='caveats', to='annotations.Figure'),
        ),
    ]
