# Generated by Django 3.0.6 on 2021-02-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_download'),
        ('caveats', '0005_add_figures'),
    ]

    operations = [
        migrations.AddField(
            model_name='caveat',
            name='downloads',
            field=models.ManyToManyField(related_name='caveats', to='annotations.Download'),
        ),
    ]
