# Generated by Django 3.2.11 on 2022-01-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caveats', '0008_alter_caveat_specifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caveat',
            name='severity',
            field=models.TextField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('critical', 'critical'), ('replaced', 'replaced')]),
        ),
    ]
