# Generated by Django 3.2.11 on 2022-01-31 15:19

from django.db import migrations


def run_data_migration(apps, schema_editor):
    Caveat = apps.get_model('caveats', 'Caveat')

    for caveat in Caveat.objects.all():
        if caveat.severity == 'medium':
            caveat.severity = 'low'
        elif caveat.severity == 'critical':
            caveat.severity = 'high'
        caveat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('caveats', '0008_alter_caveat_specifiers'),
    ]

    operations = [
        migrations.RunPython(run_data_migration),
    ]
