# Generated by Django 3.2.11 on 2022-01-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caveats', '0010_alter_caveat_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='caveat',
            name='exclude',
            field=models.TextField(blank=True, help_text='You can add multiple paths line by line. Datasets will be excluded if their path starts with one of the paths given.'),
        ),
        migrations.AddField(
            model_name='caveat',
            name='include',
            field=models.TextField(blank=True, help_text='You can add multiple paths line by line. If paths are provided, datasets will only be included if their path starts with one of the paths given.'),
        ),
    ]
