# Generated by Django 3.2.11 on 2022-07-05 12:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caveats', '0012_alter_caveat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='caveat',
            name='resources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None),
        ),
    ]
