# Generated by Django 3.2.15 on 2023-03-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caveats', '0014_caveat_message'),
    ]

    def run_data_migration(apps, schema_editor):
        Caveat = apps.get_model('caveats', 'Caveat')

        for caveat in Caveat.objects.all():
            if caveat.severity == 'replaced':
                caveat.severity = 'high'
            caveat.save()

    operations = [
        migrations.RunPython(run_data_migration),
        migrations.AlterField(
            model_name='caveat',
            name='severity',
            field=models.TextField(choices=[('low', 'low'), ('high', 'high')]),
        ),
    ]
