# Generated by Django 4.2.4 on 2024-04-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caveats', '0015_alter_caveat_severity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caveat',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='caveat',
            name='category',
            field=models.TextField(choices=[('note', 'note'), ('issue', 'issue')], default='issue'),
        ),
        migrations.AlterField(
            model_name='caveat',
            name='message',
            field=models.TextField(blank=True, choices=[('can_be_used', 'Affected datasets can still be used for simulations or research.'), ('do_not_use', 'Affected datasets should not be used until this caveat is resolved.'), ('replaced', 'Please use the replaced datasets for new simulations or research.')]),
        ),
        migrations.AlterField(
            model_name='caveat',
            name='severity',
            field=models.TextField(blank=True, choices=[('low', 'low'), ('high', 'high')]),
        ),
        migrations.AlterField(
            model_name='caveat',
            name='status',
            field=models.TextField(blank=True, choices=[('new', 'new'), ('on_hold', 'on hold'), ('resolved', 'resolved'), ('wont_fix', "won't fix")]),
        ),
    ]
