# Generated by Django 4.2.4 on 2024-07-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caveats', '0016_alter_caveat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='caveat',
            name='message',
            field=models.TextField(blank=True, choices=[('can_be_used', 'Affected datasets can still be used for simulations or research.'), ('do_not_use', 'Affected datasets should not be used until this issue is resolved.'), ('replaced', 'Please use the replaced datasets for new simulations or research.')]),
        ),
        migrations.AlterField(
            model_name='caveat',
            name='severity',
            field=models.TextField(blank=True, choices=[('low', 'low'), ('high', 'high')], default='low'),
        ),
        migrations.AlterField(
            model_name='caveat',
            name='status',
            field=models.TextField(blank=True, choices=[('new', 'new'), ('on_hold', 'on hold'), ('resolved', 'resolved'), ('wont_fix', "won't fix")], default='new'),
        ),
    ]
