# Generated by Django 3.2.15 on 2023-03-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facet',
            old_name='attribute',
            new_name='identifier',
        ),
    ]
