# Generated by Django 3.0.6 on 2021-04-01 10:38

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0003_add_created_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('specifiers', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('datasets', django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, default=list, size=None)),
                ('version_after', models.CharField(blank=True, max_length=8)),
                ('version_before', models.CharField(blank=True, max_length=8)),
                ('downloads', models.ManyToManyField(related_name='annotations', to='annotations.Download')),
                ('figures', models.ManyToManyField(related_name='annotations', to='annotations.Figure')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
