# Generated by Django 3.0.6 on 2021-04-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0004_annotation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('identifier', models.URLField()),
                ('identifier_type', models.TextField(choices=[('doi', 'DOI'), ('url', 'URL')])),
                ('reference_type', models.TextField(choices=[('ISIPEDIA', 'ISIpedia'), ('OTHER', 'Other')])),
            ],
            options={
                'ordering': ('title',),
            },
        ),
    ]
