# Generated by Django 3.0.6 on 2021-04-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0005_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='references',
            field=models.ManyToManyField(related_name='annotations', to='annotations.Reference'),
        ),
    ]
