# Generated by Django 3.2.5 on 2021-07-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0006_annotation_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='specifiers',
            field=models.JSONField(default=dict),
        ),
    ]
