# Generated by Django 3.2.11 on 2022-01-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0007_alter_annotation_specifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='figure',
            name='width',
            field=models.IntegerField(default=12, help_text='Width in columns (12 is full width).'),
        ),
    ]
