# Generated by Django 3.2.15 on 2022-10-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0008_figure_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='reference_type',
            field=models.TextField(choices=[('ISIPEDIA', 'ISIpedia'), ('EVALUATION', 'Evaluation'), ('OTHER', 'Other')]),
        ),
    ]
